config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: :show

  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  scope :by_best_ratings, -> { order('average_rating DESC NULLS LAST') }

  def self.import(io)
    now = Time.current

    recipes_attributes = io.readlines.map do |line|
      properties = JSON.parse(line, symbolize_names: true)

      {
        name: properties[:name],
        author: properties[:author],
        image_url: properties[:image],
        difficulty: properties[:difficulty],
        budget: properties[:budget],
        servings: properties[:people_quantity],
        preparation_time: properties[:prep_time],
        cooking_time: properties[:cook_time],
        total_time: properties[:total_time],
        average_rating: properties[:rate],
        ingredients: properties[:ingredients],
        created_at: now,
        updated_at: now
      }
    end

    Recipe.insert_all recipes_attributes
  end

  # Search recipe that are possible to make with the provided ingredients
  # if a recipe ingredient is not in the list the recipe will not be returned
  #
  # @param ingredients [String] a comma separated list of ingredients
  def self.search_all_matching_ingredients(ingredients)
    ingredients = ingredients.split(',').map do |ingredient|
      "%#{ingredient.strip}%"
    end

    str = <<~SQL
      ingredients = array(
        select ingredient from unnest(ingredients) as ingredient
        where ingredient ILIKE ANY(array[:ingredients])
      )
    SQL

    self.where(str, ingredients: ingredients)
  end

  def image_url
    super.presence || 'default-unsplash.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: :show

  def index
    results = search(Recipe.by_best_ratings)
    @recipes = paginate(results)
  end

  def show
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def paginate(relation)
    @pagy, records = pagy(relation, items: 24)
    records
  end

  def search(relation)
    return relation unless search_params

    relation.search_all_matching_ingredients(search_params)
  end

  def search_params
    params[:query]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def rating_stars(recipe)
    rating = recipe.average_rating.to_i.floor
    rating_label = "Rating: #{rating} out of 5 stars"

    tag.div(class:'leading-none text-green-300 flex items-center', role: 'img', aria: { label: rating_label }) do
      capture do
        5.times do |n|
          icon = if n < rating
            'icons/star-full.svg'
          else
            'icons/star-empty.svg'
          end

          concat inline_svg_tag(icon, class: 'w-3.5 h-3.5')
        end
      end
    end
  end
end

app/views/application/_list_item_layout.html.erb
<li><%= yield %></li>

app/views/application/_navbar.html.erb
<nav class="bg-white pt-6 pb-4 px-2 border-b border-gray-300 md:px-4 lg:px-10 sm:flex sm:space-x-6">
  <%= link_to root_path, class: 'flex justify-center items-center space-x-1' do %>
    <%= inline_svg_tag('icons/cake.svg', class: 'w-8 h-8 text-green-400') %>
    <h1 class="font-medium text-2xl">
      PennyFood
    </h1>
  <% end %>

  <%= form_with url: root_path, method: :get, class: 'mt-4 flex-grow sm:mt-0 lg:px-10' do |f| %>
    <%= f.label :query, "List of ingredients", class: 'sr-only' %>

    <div class="relative mt-1 rounded-md shadow-sm">
      <%= f.search_field :query,
                        value: search,
                        minlength: 3,
                        placeholder: "E.g. Nutella Creme Chorizo",
                        class: "focus:ring-green-400 focus:border-green-400 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md" %>

      <div class="absolute inset-y-0 right-0 flex items-center">
        <%= f.button name: nil, data: { test_id: 'search_button' }, class: 'block text-center leading-0 text-xl absolute top-2 right-2 text-gray-400 focus:outline-none hover:text-gray-900 transition-colors' do %>
          <%= inline_svg_tag('icons/search.svg') %>
        <% end %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pennyfood | What can I do with my fridge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "inter-font" %>
    <%= stylesheet_link_tag "tailwind" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
  </head>

  <body>
    <%= render 'navbar', search: params[:query] %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<article id="<%= dom_id recipe %>" class="shadow-sm rounded h-full bg-white overflow-hidden" >
  <%= link_to recipe_path(recipe), data: { test_id: 'show_recipe' } do %>
    <%= image_tag recipe.image_url, class: 'w-full object-cover h-32 sm:h-48' %>

    <header class="py-2 px-2">
      <h3 class="font-semibold mb-2 text-lg leading-tight"><%= recipe.name.capitalize %></h3>
      <%= rating_stars recipe %>
    </header>
  <% end %>
</article>

app/views/recipes/index.html.erb
<main class="bg-gray-100">
  <section class="container mx-auto px-4 pt-6 lg:px-12 xl:px-48">
    <ul class="grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">
      <%= render partial: "recipe", collection: @recipes, layout: "list_item_layout", cached: true %>
    </ul>

    <div class="pt-4 pb-6 text-center">
      <%= render 'shared/pagination', pagy: @pagy %>
    </div>
  </section>
</main>

app/views/recipes/show.html.erb
<main class="bg-gray-100 h-screen sm:pt-6">
  <% cache @recipe do %>
    <div class="max-w-prose mx-auto bg-white sm:rounded-md">
      <header id="recipe_header" class="px-4 py-6 border-b lg:px-12">
        <h2 class="text-center text-2xl font-medium text-gray-700"><%= @recipe.name.capitalize %></h2>

        <div class="text-sm text-gray-900 mt-4 flex justify-between">
          <%= rating_stars(@recipe) %>
          <p>Par @<%= @recipe.author %></p>
        </div>
      </header>

      <section id="recipe_details" class="px-4 py-6 lg:px-12 border-b">
        <dl class="grid grid-cols-2">
          <div class="mb-4">
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:difficulty) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.difficulty %></dd>
          </div>
          <div class="mb-4">
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:budget) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.budget %></dd>
          </div>
          <div class="mb-4">
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:servings) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.servings %></dd>
          </div>
          <div class="mb-4">
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:preparation_time) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.preparation_time %></dd>
          </div>
          <div class="mb-4">
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:cooking_time) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.cooking_time %></dd>
          </div>
          <div>
            <dt class="text-sm text-gray-500"><%= Recipe.human_attribute_name(:total_time) %></dt>
            <dd class="text-sm text-gray-900"><%= @recipe.total_time %></dd>
          </div>
        </dl>
      </section>

      <section id="recipe_ingredients" class="px-4 py-6 lg:px-12">
        <ul class="list-inside list-disc">
          <% @recipe.ingredients.each do |ingredient| %>
            <li class="text-sm text-gray-900 mb-2"><%= ingredient %></li>
          <% end %>
        </ul>
      </section>
    </div>
  <% end %>
</main>

app/views/shared/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<nav aria-label="pager" class="relative z-0 inline-flex rounded-md -space-x-px" role="navigation">
  <% if pagy.prev -%>
    <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-green-300 prev">
      <%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %>
    </span>
  <% end -%>

  <%# series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]  %>
  <% pagy.series.each do |item| -%>
    <% if item.is_a?(Integer) -%>
      <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-green-300 hidden sm:block">
        <%== link.call(item) %>
      </span>
    <% elsif item.is_a?(String) -%>
      <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-green-300 hover:text-green-300 hidden sm:block">
        <%= item %>
      </span>
    <% elsif item == :gap -%>
      <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-green-300 hidden sm:block">
        <%== pagy_t('pagy.nav.gap') %>
      </span>
    <% end -%>
  <% end -%>

  <% if pagy.next -%>
    <span class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-green-300 next">
      <%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %>
    </span>
  <% end -%>
</nav>